### ISSUE TITLE
UI Events Keyboard Events Key Values 2022-11-29 > 2023-01-31

### ISSUE THREAD

**Issue by LJWatson** [w3c/i18n-request#199] opened 2022-11-29 15:21 UTC
### Name of your specification

UI Events Keyboard Events Key Values

### URL of your specification

https://w3c.github.io/uievents-key/

### When does the review need to be finished?

2023-01-31

### What has changed since any previous review?

A self-review was carried out and the Editor found that none of the criteria applied. This is recorded on the [specification repo](https://github.com/w3c/uievents-key/issues/57#issuecomment-1301233730). There is however a note left in redsponse to the a11y self-review that may be of interest, recorded [earlier in the same issue](https://github.com/w3c/uievents-key/issues/57#issuecomment-1301231347):

>A note related to the FAST checklist item: "If technology provides internationalization support". This specification inherently defines {{KeyboardEvent/key}}
values that support international hardware, e.g., keyboards for different languages or layouts. It also defines many special keys which are given human-readable
names (like "Shift", "Control", "Home" or "ArrowLeft").
These special key values are defined as human-readable strings so that code to detect special keys can be easier to understand. While these values are
not intended to be exposed directly to users, there is nothing preventing that. Apps that choose to expose these values would need to determine whether
or not it is appropriate to translate these strings for presentation (e.g.: presenting "Backspace" as "Suppr. arrière" for French users).

We are hoping to transition to CR in February.

**Comment by LJWatson** [comment] 2023-01-30 17:58
@xfq do you know when your review might be completed? With thanks.

**Comment by aphillips** [comment] 2023-02-03 00:13
@LJWatson Our review was completed on 9 December. There was one issue, which is w3c/uievents-code#36. I just added a comment to that issue in case there may be any confusion about it. I also note that the issue is still present in your spec and that the raised issue is editorial. Please let me know if you have any questions or concerns!!

_this is [I18N-ACTION-1236](https://www.w3.org/International/track/actions/1236)_

**Comment by aphillips** [comment] 2023-02-03 17:12
@LJWatson  I18N completed a review on 9 December and there are two open issues as a result. These are: w3c/uievents-key#58 and w3c/uievents-key#59. Neither seems to have been addressed in your current spec.

In the course of checking on this, I happened to notice that this spec also has a minor problem with Unicode character references. I filed a bug in ***our*** repo (as w3c/i18n-activity#1652) which will likely be forwarded to you next week.

By the way, you can check the status of your issues in the [review tracker tool](https://w3c.github.io/horizontal-issue-tracker/index?repo=w3c/i18n-activity). Also note that this issue shows history on our Review Radar--in this case that the request was moved to "Awaiting Comment Resolution" on 9 December. That state is a completed review with open issues (vs. "Completed", which is when all our issues are closed)

**Comment by LJWatson** [comment] 2023-02-21 10:21
Thanks @aphillips and apologies for the unnecessary chase. My fault entirely for looking in the wrong places for information.

**Comment by aphillips** [comment] 2024-11-05 15:50
Both filed issues were completed. Marking this complete.

**Closed as completed** 2024-11-05 15:52 UTC
Labels: REVIEW REQUESTED, LC, close?
